Add windows paste functionality
Iilun/survey pull request #23
Opened 2024-12-05 15:38 UTC by mkarten

2025-02-25 19:31 UTC, KT0O requested changes

2025-02-25 19:31 UTC, KT0O commented on terminal/runereader_windows.go
> +	getClipboardData = dll.NewProc("GetClipboardData")
Is this necessary ?

2025-02-25 19:31 UTC, KT0O commented on terminal/runereader.go
> -
Not useful

2025-02-25 19:50 UTC, KT0O commented
Apart from these minor changes, LGTM

2025-02-26 09:12 UTC, Iilun approved these changes

2025-02-26 09:30 UTC, merged